In [2]:
import numpy as np

In [3]:
# numpy 기초

In [6]:
data = [1,2,3]
ar = np.array(data,dtype = "float32")
ar1 = np.array([range(i,i+3) for i in data])
ar2 = np.full((3,5),3.14)
ar3 = np.arange(0,20,2)
ar4 = np.linspace(0,1,3)
ar5 = np.random.random((3,3)) # 0와 1 사이
ar6 = np.random.randint(0,100,(3,3)) # 0과 100 사이
ar7 = np.eye(3)
print(ar)
print(ar1)
print(ar2)
print(ar3)
print(ar4)
print(ar5)
print(ar6)

[1. 2. 3.]
[[1 2 3]
 [2 3 4]
 [3 4 5]]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.5 1. ]
[[0.60581924 0.66781494 0.44873963]
 [0.56511993 0.68381022 0.21721949]
 [0.4306854  0.95492661 0.04465873]]
[[15 42  7]
 [16 55 63]
 [78 42 96]]


In [12]:
# 배열 속성
x = np.array([range(i,i+3) for i in data])
print(x.ndim) # 배열의 차원
print(x.shape)
print(x.size)

2
(3, 3)
9


In [13]:
# 배열 인덱싱
y = np.array([2,4,6,8,10])
print(y[0],y[-2])

2 8


In [16]:
# 배열 슬라이싱
x = np.arange(10) # [0 1 2 3 4 5 6 7 8 9]
x[4:8]

array([4, 5, 6, 7])

In [25]:
# 배열 결합
x = [1,2,3,4]
y = np.arange(4)
z = np.concatenate([x,y])
print(z)

a = np.vstack([x,y]) # 수직 스택 axis = 0
b = np.hstack([x,y]) # 수평 스택
print(a)
print(b)

[1 2 3 4 0 1 2 3]
[[1 2 3 4]
 [0 1 2 3]]
[1 2 3 4 0 1 2 3]


In [34]:
# 배열 분할
x1,x2,x3 = np.split(x,[1,3]) # (대상 리스트, 분할 위치)
print(x1,x2,x3)

up,down = np.vsplit(a,2)
left,right = np.hsplit(a,2)
print(up,down)
print(left)

[1] [2 3] [4]
[[1 2 3 4]] [[0 1 2 3]]
[[1 2]
 [0 1]]
