In [2]:
import numpy as np

In [4]:
# 배열 산술 연산
x = np.arange(4)
print(x + 10)
print(x * 2)
print(x // 2) # 몫만 산출
print(x % 2) # 나머지

# 이외에도 복소수, 삼각함수, 역삼각함수, 지수함수(np.exp(x),np.power(3,x)->3^x) 등 제공

[10 11 12 13]
[0 2 4 6]
[0 0 1 1]
[0 1 0 1]


In [15]:
# out 인자 # out에 결과 저장 # 시간 절감
x = np.arange(5)
y= np.zeros(5)
print(y)

np.log(x,out = y)
print(y)

[0. 0. 0. 0. 0.]
[      -inf 0.         0.69314718 1.09861229 1.38629436]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log
  


In [22]:
x = np.arange(1,5)
print(np.add.reduce(x)) # 연산 반복 적용
print(np.sum(x))
print(np.max(x))
print(x.min(axis = 0)) # None은 전체

10
10
4
1


In [ ]:
# 브로드캐스팅 연산: 다른 크기의 리스트끼리도 연산 수행 가능 # 높은 차원에 맞춤

In [24]:
# 비교연산자
x = np.arange(10)
print(np.any(x<5)) # or
print(np.all(x<5)) # and

# np.equal, not_equal, less, less_equal, greater, greater_equal

False

In [25]:
# 팬시 인덱싱
a = np.arange(10)
b = np.array([3,6,9])
a[b]

array([3, 6, 9])

In [31]:
# 정렬
x = np.array([3,2,1])
print(np.sort(x))
x.sort() # x 자체가 바뀜
print(np.argsort(x)) # 정렬된 요소의 인덱스 반환

# 내림차순 정렬
print(np.sort(x)[::-1])

# 다차원 배열 정렬
x = np.array([[2,0,6],[7,3,4]])
print(np.sort(x,axis=0)) # 열 기준 정렬

[1 2 3]
[0 1 2]
[3 2 1]
[[2 0 4]
 [7 3 6]]
